name: Auto-merge when green
on:
  pull_request:
    types: [labeled, synchronize, reopened, ready_for_review]
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    if: github.event_name != 'check_suite' || github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request
              ?? (context.payload.check_suite?.pull_requests?.[0]
                  ? (await github.rest.pulls.get({ ...context.repo, pull_number: context.payload.check_suite.pull_requests[0].number })).data
                  : null);
            if (!pr || pr.draft) return;
            if (!pr.labels.some(l => l.name.toLowerCase() === 'automerge')) return;
            const { data: status } = await github.rest.repos.getCombinedStatusForRef({ ...context.repo, ref: pr.head.sha });
            if (status.state !== 'success') return;
            await github.rest.pulls.merge({ ...context.repo, pull_number: pr.number, merge_method: 'squash' });
